terra: Add vaa_payload crate
wormhole-foundation/wormhole pull request #1001
Opened 2022-03-15 09:55 UTC by jynnantonix

The vaa_payload crate implements a serde data format for VAA payloads.
This will let us replace all the hand-rolled serialization code with
auto-generated code, which is less error-prone and easier to review.

2022-04-12 07:35 UTC, kcsongor commented
Why is this only for terra? Can't we use it in solana too?

2022-04-12 07:48 UTC, kcsongor commented on terra/packages/vaa_payload/src/lib.rs
> +//! Enums are encoded as a single byte identifying the variant followed by the serialization of the
What's the rationale for this encoding? Did you find any VAA types that encode enums in this way? The only enum-like thing that comes to mind is the choice between the different types of payloads, such as "token bridge contract upgrade" and "nft bridge transfer", but discriminating between these is not done by an encoded enum tag, or any other identifier. In fact, there's no explicit discriminator, and I'm not even sure if the VAA grammar used just by the token bridge itself is unambiguous. Even if it's unambiguous, an arbitrary VAA certainly can't be parsed into an appropriate payload type without backtracking.

2022-04-12 07:55 UTC, kcsongor commented on terra/packages/vaa_payload/src/lib.rs
> +//! Enums are encoded as a single byte identifying the variant followed by the serialization of the
Actually, I take that back. The token bridge and NFT bridge payloads are encoded in this way.

2022-04-13 06:51 UTC, jynnantonix commented
> Why is this only for terra? Can't we use it in solana too?

No particular reason.  I just hadn't looked at the solana code at all and so didn't think about making this more general purpose.  I'll move it into the sdk directory.

2022-05-27 06:10 UTC, jynnantonix commented
I think I'm just going to close this.  The goal was to avoid having to manually write parsing code for the various VAA messages we already have and I'm not sure about the benefit of moving it into the sdk.  People building on top of wormhole should use a proper schema for their payloads rather than the hand rolled one we're using for VAAs.

2022-06-27 09:16 UTC, jynnantonix commented
I've moved the crate into the sdk/rust directory and also added support for strings and maps.

2022-06-28 04:46 UTC, jynnantonix commented
> could we get the byte_utils.rs from terra/contracts/wormhole/src added into here as well? I use state.rs and byte_utils.rs in every single rust contract I build...

The purpose of this crate is to be a replacement for byte_utils.rs so I don't think moving it here helps us with that goal.

2022-09-28 10:22 UTC, hendrikhofstadt requested changes

2022-09-28 10:22 UTC, hendrikhofstadt commented on sdk/rust/vaa_payload/src/lib.rs
> +//! to fit in a single byte it cannot be longer than 255 bytes.
fields like the VAA payload don't have a length field and can have unlimited length (till the end of the packet)

2022-09-28 10:22 UTC, hendrikhofstadt commented on sdk/rust/vaa_payload/src/lib.rs
> +        map: BTreeMap<u32, u32>,
not part of the spec (https://github.com/wormhole-foundation/wormhole/blob/dev.v2/whitepapers/0001_generic_message_passing.md)

2022-09-29 09:00 UTC, hendrikhofstadt commented on sdk/rust/vaa_payload/src/lib.rs
> +//! to fit in a single byte it cannot be longer than 255 bytes.
That sounds good

2022-09-29 09:49 UTC, hendrikhofstadt commented on sdk/rust/vaa_payload/src/lib.rs
> +        map: BTreeMap<u32, u32>,
I missed that this is in tests only.

2022-09-29 09:49 UTC, hendrikhofstadt approved these changes

2022-11-28 23:10 UTC, jynnantonix commented
Superseeded by #1919

2022-11-28 23:10 UTC, closed without merging