simplify quorum calculation
wormhole-foundation/wormhole pull request #1536
Opened 2022-09-06 19:33 UTC by tbjump

2022-09-06 19:34 UTC, kcsongor approved these changes

2022-09-07 15:01 UTC, jumpsiegel approved these changes

2022-09-08 09:57 UTC, claudijd commented on cosmwasm/contracts/wormhole/src/state.rs
> +        ((self.addresses.len() * 2) / 3) + 1
Do each of the chains we're modifying quorum calculation here have independant quorum unit-tests to ensure that this doesn't cause a regression?  I'm thinking of what exists for Solidity / Guardians:

- https://github.com/wormhole-foundation/wormhole/blob/dev.v2/node/pkg/processor/quorum_test.go
- https://github.com/wormhole-foundation/wormhole/blob/dev.v2/ethereum/forge-test/Messages.t.sol#L13-L29

Where possible, I'd love to see the core trust assumptions, like quorum, well unit-tested on all chains.  This is especially true when making medications to those implementations to help prevent regression scenarios.

2022-09-08 09:57 UTC, claudijd commented on cosmwasm/contracts/wormhole/src/state.rs
> +        ((self.addresses.len() * 2) / 3) + 1
That said, the math is pretty straight forward, so as a function of the review, I agree with the implementation changes, would just like to see associated test coverage.

2022-10-26 12:23 UTC, kcsongor approved these changes

2022-10-26 12:24 UTC, evan-gray requested changes
I would approve, but given the criticality of the code can you provide the unit tests that cover each of these?

2022-11-15 00:14 UTC, tbjump commented
Unit tests are here: https://github.com/wormhole-foundation/wormhole/blob/dedcea34af2c6760882c019957d51359aef186f7/cosmwasm/contracts/wormhole/src/testing/tests.rs#L6

2022-11-15 00:16 UTC, kcsongor submitted a review, later dismissed

2022-11-15 01:08 UTC, jynnantonix approved these changes

2022-11-15 02:42 UTC, jynnantonix approved these changes

2022-11-24 03:30 UTC, jynnantonix submitted a review, later dismissed

2022-11-30 15:50 UTC, hendrikhofstadt commented
Are we 100% sure this behaves the same in the Solana bpf runtime?

2023-01-11 17:10 UTC, evan-gray commented
Discussed with @jumpsiegel and @hendrikhofstadt and we would prefer not to change these critical calculations at this time.

2023-01-11 17:10 UTC, closed without merging