XPLA Mainnet Deploy
wormhole-foundation/wormhole pull request #1703
Opened 2022-10-10 19:37 UTC by bruce-riley

2022-10-10 21:11 UTC, ckeun approved these changes

2022-10-11 18:25 UTC, ckeun submitted a review, later dismissed

2022-10-12 09:56 UTC, evan-gray requested changes
Commenting to hold as #1715 identifies issues that will require a new token bridge deployment.

2022-10-12 20:32 UTC, kev1n-peters approved these changes

2022-10-12 20:46 UTC, evan-gray approved these changes

2022-10-12 20:47 UTC, merged