evm: add token and nft bridge interface
wormhole-foundation/wormhole pull request #1710
Opened 2022-10-11 15:43 UTC by gator-boi

2022-10-26 21:20 UTC, a5-pickle submitted a review, later dismissed

2022-10-28 12:35 UTC, evan-gray requested changes
Standby, @kcsongor and I have a sweet test idea to make sure these match the contracts!

2022-10-28 16:21 UTC, kcsongor approved these changes

2022-10-28 16:28 UTC, evan-gray approved these changes
🙌

2022-10-28 16:28 UTC, merged