Script changes for acala upgrade
wormhole-foundation/wormhole pull request #1726
Opened 2022-10-13 12:52 UTC by bruce-riley

2022-10-13 12:58 UTC, kcsongor requested changes
I think we should move away from the `deploy-*-only` pattern as it abuses the migration logic of truffle. We already have implementation deploy scripts for all of the contracts here: https://github.com/wormhole-foundation/wormhole/tree/dev.v2/ethereum/scripts, which can be run by eg
```
npx truffle scripts/deploy_core_bridge.js --network ethereum
```
so I think we should just use those and remove all of the `-implementation-only` migrations.
(FWIW the https://github.com/wormhole-foundation/wormhole/blob/dev.v2/ethereum/upgrade script does this under the hood. Not super well documented, but it can be used to deploy a contract by running `./upgrade mainnet TokenBridge ethereum`. I want to document it better and add a usage string etc.)

2022-10-13 13:37 UTC, bruce-riley commented
Removed the new deploy scripts

2022-10-13 13:47 UTC, kcsongor submitted a review, later dismissed

2022-10-13 14:56 UTC, ckeun submitted a review, later dismissed

2022-10-13 15:55 UTC, ckeun approved these changes

2022-10-20 13:25 UTC, panoel submitted a review, later dismissed

2022-10-20 16:53 UTC, panoel approved these changes

2022-10-20 18:20 UTC, panoel approved these changes

2022-10-21 18:46 UTC, ckeun approved these changes

2022-10-21 18:52 UTC, merged