node: governor updates for Aptos
wormhole-foundation/wormhole pull request #1740
Opened 2022-10-15 14:26 UTC by bruce-riley

2022-10-15 14:29 UTC, kcsongor submitted a review, later dismissed

2022-10-15 15:47 UTC, hendrikhofstadt approved these changes
This could lead to silent failures should coingecko ever change IDs so I'd recommend actively monitoring this

2022-10-16 21:57 UTC, claudijd commented on node/pkg/governor/mainnet_chains.go
> +		chainConfigEntry{emitterChainID: vaa.ChainIDAptos, dailyLimit: 5_000_000, bigTransactionSize: 500_000},
Guardian feedback from Chainnode and seconded by Inotel was $1M/$100K.

2022-10-16 21:58 UTC, claudijd requested changes
Switch aptos limit to $1M/$100K per Guardian feedback

2022-10-16 22:04 UTC, claudijd approved these changes

2022-10-16 22:06 UTC, kcsongor approved these changes

2022-10-16 22:20 UTC, merged