ci: unscoped package check robustness improvements
wormhole-foundation/wormhole pull request #1774
Opened 2022-10-20 23:05 UTC by tbjump

This change tries to improve the previous bash script by
1) supporting spaces and other special characters in file paths
2) using jq instead of a simple grep to parse the json
3) being more restrictive in the regexes on what to allow to pass through

Would like to get the feedback from the bash wiz though

2022-10-21 01:48 UTC, evan-gray requested changes
Should this be different from the dockerfile check? It was a copy paste of that.

2022-10-22 00:42 UTC, tbjump commented
> Should this be different from the dockerfile check? It was a copy paste of that.

I changed it in `./scripts/check-docker-pin.sh` as well.

2022-10-28 11:38 UTC, evan-gray requested changes
The docker check changed recently, can you please resolve merge conflicts.

2022-10-28 12:13 UTC, kcsongor commented on scripts/check-docker-pin.sh
> +find . -type f -name 'Dockerfile*' -print0 | xargs -r -0 grep -s "FROM" | egrep -v 'sha256|scratch|solana|aptos AS (builder|ci_tests|tests)'
why change from `git ls-files`? `find` is much slower and will show false positives (when run locally, in the presence of build artifacts and testing stuff)

2023-01-11 17:13 UTC, closed without merging