Node: Arbitrum poller failling without details
wormhole-foundation/wormhole pull request #1836
Opened 2022-10-31 22:34 UTC by bruce-riley

The Arbitrum poller is occasionally failing, but the error text is not getting logged when the runnable dies. 

Additionally, the poller retries three times before dying, but we are not seeing the log error from any of them. Adding a 250 ms delay between retries.

Change-Id: Id067d0be18a7c391ef90a82cc78f0684c72ab2ad

2022-11-01 13:08 UTC, panoel submitted a review, later dismissed

2022-11-01 15:17 UTC, hendrikhofstadt requested changes
What's the exact motivation behind the delay? Please add a comment explaining it as well.

2022-11-02 09:51 UTC, hendrikhofstadt approved these changes

2022-11-02 12:54 UTC, panoel approved these changes

2022-11-02 13:24 UTC, merged