whitepaper: add whitepaper explaining guardian key usage
wormhole-foundation/wormhole pull request #1960
Opened 2022-11-18 02:38 UTC by tbjump

2022-11-18 12:18 UTC, kcsongor submitted a review, later dismissed
Great! one small suggestion: the title of the document should be Avoiding message confusion, or something along those lines, as it's quite specific to solving that problem

2022-11-18 12:18 UTC, kcsongor commented on whitepapers/0009_guardian_key.md
> +* v2 (batchVAA): `double-Keccak256(version | Keccak256(hash1 | hash2 | ... | hash_n))`, where `|` stands for concatenation.
didn't the final design end up with

```
keccak256(version | keccak256(...)))
```

2022-11-18 14:09 UTC, evan-gray requested changes
@hendrikhofstadt thoughts on whether this is something for a whitepaper? feels more like an issue description and something that should be in the comments of p2p.go 🤔 thoughts @tbjump?

2022-11-18 14:31 UTC, tbjump commented
> @hendrikhofstadt thoughts on whether this is something for a whitepaper? feels more like an issue description and something that should be in the comments of p2p.go 🤔 thoughts @tbjump?

The scope of this is more than p2p.go because the guardian key is used also in the processor for signing observations and *could* be used outside of the guardiand as well. E.g. yesterday there was discussion about using it for wormchain ceremony. I think given the importance and potential for errors, a central whitepaper is appropriate.

2022-11-18 14:49 UTC, claudijd submitted a review, later dismissed

2022-11-22 03:22 UTC, tbjump commented
@evan-gray wdyt? good to merge?

2022-11-22 14:30 UTC, njkumr commented on whitepapers/0009_guardian_key.md
> +* v2 (batchVAA): `double-Keccak256(version | Keccak256(hash1 | hash2 | ... | hash_n))`, where `|` stands for concatenation.
batch Vaa hash is for now calculated as `double-Keccak256(version | Keccak256(hash1 | hash2 | ... | hash_n))` where hash1 = double-Keccak256(observation1) and so on...

2022-11-23 19:49 UTC, evan-gray approved these changes
Concur with @tbjump that key usage may extend beyond node p2p specific code so documenting the expectations here seems appropriate.

2022-11-23 19:51 UTC, mtjmp approved these changes

2022-11-23 19:51 UTC, merged