sdk: Add unit-tests for quorum calculation
wormhole-foundation/wormhole pull request #2127
Opened 2022-12-15 18:44 UTC by claudijd

This is an essential part of quorum determination within the Guardian.  I thought I had done this at some point, but maybe it got lost in the migration from the Guardian into the SDK.  Adding it back and simplifying the math to match where it's been simplified in other places.

2022-12-15 18:51 UTC, tbjump submitted a review, later dismissed
lgtm. pls make sure all ci checks pass.

2022-12-15 19:35 UTC, hendrikhofstadt requested changes
+1 for adding tests there.
We have this test here https://github.com/wormhole-foundation/wormhole/blob/fba2f48deef2c21991d8acd04f1c9b9cfaf76fdd/node/pkg/processor/quorum_test.go. Do we want to move it?

2022-12-19 05:00 UTC, jynnantonix approved these changes

2022-12-19 22:56 UTC, bruce-riley approved these changes

2022-12-27 18:24 UTC, heyitaki approved these changes

2022-12-27 18:27 UTC, merged