Node/Acct: Renaming
wormhole-foundation/wormhole pull request #2245
Opened 2023-01-13 20:15 UTC by bruce-riley

Change "Accounting" to "Accountant".

Change-Id: I20783b4ae4e445a54d45280e19332af87336a92a

2023-01-16 05:55 UTC, jynnantonix commented
I tried changing the base branch of the PR to #2181 but it looks like one of them has been rebased on main while the other one has not.  Since this PR includes *all* the changes from #2181 it's a bit hard to see exactly what's different.

I suggest using the graphite cli to stack this PR on top of #2181.  Otherwise we can wait until after #2181 is merged and then rebase this PR before reviewing.

2023-01-16 09:00 UTC, hendrikhofstadt requested changes
pls rebase

2023-01-16 15:04 UTC, hendrikhofstadt approved these changes

2023-01-17 08:09 UTC, jynnantonix approved these changes

2023-01-17 13:30 UTC, merged