cosmwasm: Rename accounting -> accounting
wormhole-foundation/wormhole pull request #2261
Opened 2023-01-18 09:07 UTC by jynnantonix

2023-01-18 09:07 UTC, jynnantonix commented
Current dependencies on/for this PR:
* main
  * **PR #2207** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2207" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2216** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2216" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #2241** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2241" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #2261** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2261" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2261?utm_source=stack-comment).

2023-01-18 14:37 UTC, hendrikhofstadt approved these changes

2023-01-18 20:54 UTC, bruce-riley approved these changes

2023-01-23 14:37 UTC, a5-pickle requested changes
I'm changing my review because there is an issue running the Tilt Github action. I've tried re-running this several times, and every time it fails. @jynnantonix would you be able to look into this?

2023-01-23 16:49 UTC, evan-gray commented
> I'm changing my review because there is an issue running the Tilt Github action. I've tried re-running this several times, and every time it fails. @jynnantonix would you be able to look into this?

I think this is an issue with the expectations of wasm names in the terra deploy, I'll try to push a fix today 🙂

2023-01-23 21:03 UTC, bruce-riley approved these changes

2023-01-23 21:23 UTC, bruce-riley approved these changes

2023-01-23 21:41 UTC, a5-pickle approved these changes

2023-01-23 21:42 UTC, merged