sdk: Aptos NFT SDK
wormhole-foundation/wormhole pull request #2267
Opened 2023-01-19 07:37 UTC by heyitaki

This PR adds a JS SDK for the Aptos NFT bridge.

Outstanding work for future PRs:
- implement `getForeignAsset` pending discussion
- implement `getEmitterAddressAptos`
- add additional test to transfer native Aptos NFT to Solana and back
- clean up Aptos token bridge SDK
- add documentation

2023-01-19 08:42 UTC, heyitaki commented
Formatting commit might seem random, but something in there was causing the `lint-and-tests` check to fail

2023-01-23 15:10 UTC, kev1n-peters commented on sdk/js/src/utils/consts.ts
> +      "0x1bdffae984043833ed7fe223f7af7a3f8902d04129b14f801823e64827da7130",
I don't think this is actually deployed in testnet

2023-02-01 20:20 UTC, heyitaki commented
`getEmitterAddressAptos` is intentionally left unimplemented as there is no good way to fetch the emitter address from the Aptos core bridge, which uses sequential IDs given to each new registered emitter. Because the Aptos SDK doesn't return [types of values in account resources](https://aptos-labs.github.io/ts-sdk-doc/types/Types.MoveStructValue.html), there is no way to programmatically search for and find the emitter address, since we would not be able to tell it apart from another struct with the same fields.

2023-02-03 14:10 UTC, kev1n-peters commented on sdk/js/src/nft_bridge/__tests__/aptos-integration.ts
> +    // transfer NFT from Aptos to Solana
Should be `to Ethereum`

2023-02-03 14:18 UTC, kev1n-peters commented on sdk/js/src/utils/aptos.ts
> + * and mint a singl token for each transferred NFT. This method derives the
singl -> single

2023-02-06 15:11 UTC, evan-gray requested changes

2023-02-06 15:11 UTC, evan-gray commented on solana/keys/solana-devne2.json
> +[118,84,4,83,83,183,31,184,20,172,95,146,7,107,141,183,124,196,66,246,215,243,54,61,118,188,239,237,168,108,227,169,93,119,180,216,9,169,30,4,167,235,188,51,70,24,181,227,189,59,163,161,252,219,17,10
`devne` ? typo

2023-02-06 15:37 UTC, kev1n-peters submitted a review, later dismissed

2023-02-06 17:24 UTC, heyitaki commented on sdk/js/src/nft_bridge/getForeignAsset.ts
> +  originAddress: Uint8Array
I think you're right, we should be taking in token id and iterate through token creation events until `name === tokenId`; will push fix and a test shortly

2023-02-07 20:40 UTC, evan-gray approved these changes
Approving based on a cursory review and testing. Definitely some complexity here that would benefit from future unit tests.

2023-02-08 16:19 UTC, evan-gray approved these changes

2023-02-08 16:22 UTC, a5-pickle approved these changes
Reviewed changes in _solana_ subdirectory.

2023-02-09 15:26 UTC, a5-pickle submitted a review, later dismissed

2023-02-10 17:27 UTC, evan-gray approved these changes

2023-02-10 17:27 UTC, kev1n-peters approved these changes

2023-02-10 17:31 UTC, a5-pickle approved these changes

2023-02-10 17:35 UTC, merged