wormchain - contracts deploy CI test
wormhole-foundation/wormhole pull request #2301
Opened 2023-01-26 22:54 UTC by justinschuldt

Adds a shell script that starts up a local wormchain node and then deploys contracts and runs tests, so that it can be run in CI.
Adds the new job to CI.

2023-01-26 22:55 UTC, justinschuldt commented
Current dependencies on/for this PR:
* main
  * **PR #2296** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2296" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2297** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2297" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #2298** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2298" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #2299** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2299" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #2300** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2300" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #2301** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2301" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2301?utm_source=stack-comment).

2023-01-26 22:55 UTC, justinschuldt commented
Current dependencies on/for this PR:
* main
  * **PR #2296** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2296" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2297** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2297" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #2298** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2298" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #2299** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2299" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #2300** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2300" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #2301** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2301" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2301?utm_source=stack-comment).

2023-01-27 15:25 UTC, conorpp approved these changes

2023-01-30 16:17 UTC, justinschuldt commented
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: mPfcRG7PvNPnESsfPBuJ.
See details on [graphite.dev](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/2301)

2023-01-30 18:40 UTC, evan-gray requested changes

2023-01-30 18:40 UTC, evan-gray commented on .github/workflows/build.yml
> +<<<<<<< HEAD
Merge conflict committed?

2023-01-30 19:39 UTC, justinschuldt commented on .github/workflows/build.yml
> +<<<<<<< HEAD
wow, did that with Graphite. Fixed.

2023-02-01 16:23 UTC, evan-gray commented
Closing after discussion with @justinschuldt, this is adequately covered by accountant e2e in tilt.

2023-02-01 16:23 UTC, closed without merging