accountant: use token bridge governance vaa to modify balances
wormhole-foundation/wormhole pull request #2371
Opened 2023-02-13 21:06 UTC by conorpp

2023-02-14 05:29 UTC, jynnantonix approved these changes
Overall looks good to me.  Just have a few minor comments.

2023-02-14 05:29 UTC, jynnantonix commented on sdk/rust/core/src/token.rs
> +        reason: [u8; 32],       // 110
We have the `arraystring` module for this (see also `Message::AssetMeta`):

```suggestion
        #[serde(with = "crate::arraystring")]
        reason: BString,       // 110
```

2023-02-14 05:29 UTC, jynnantonix commented on cosmwasm/contracts/global-accountant/.cargo/config
> +strip = true
I feel like this kind of thing should go in the workspace Cargo.toml rather than here.

2023-02-14 05:29 UTC, jynnantonix commented on cosmwasm/packages/accountant/src/state.rs
> +    #[serde(with = "fixed_bytes_as_string_serde")]
We've used `#[serde(with = "hex")]` in other places for this: https://github.com/wormhole-foundation/wormhole/blob/71188d66d113373a81b88e2e9899d6ae21b7ece8/cosmwasm/packages/accountant/src/state/addr.rs#L12-L19

Can also consider leaving it as a String or BString if we take my suggestion to use "crate::arraystring" above.

2023-02-14 05:29 UTC, jynnantonix commented on sdk/vaa/payloads.go
> +		Amount        *big.Int
I believe we're using the [holiman/uint256 package](https://pkg.go.dev/github.com/holiman/uint256) for this elsewhere.

The `uint256.Int` type has a [`Bytes32()`](https://pkg.go.dev/github.com/holiman/uint256#Int.Bytes32) function that should make serialization easier.

2023-02-14 05:31 UTC, jynnantonix approved these changes
Overall looks good to me.  Just have a few minor comments.

2023-02-14 12:30 UTC, hendrikhofstadt requested changes
See inline comments

2023-02-14 13:22 UTC, bruce-riley approved these changes

2023-02-14 13:22 UTC, bruce-riley commented on proto/node/v1/node.proto
> +  // The amount to be modified.
Can you put a comment saying the format of the amount (decimal shift applied or not)?

2023-02-14 13:22 UTC, bruce-riley commented
I only reviewed the go code.

2023-02-14 16:46 UTC, conorpp commented on cosmwasm/contracts/global-accountant/src/contract.rs
> +        .add_attribute("owner", info.sender.clone());
added

2023-02-14 16:48 UTC, conorpp commented on cosmwasm/contracts/global-accountant/src/contract.rs
> +    let evt = if (body.emitter_chain == Chain::Solana || body.emitter_chain == Chain::Wormchain)
I was thinking to allow it preemptively but i'll remove and we can update later.

2023-02-15 02:20 UTC, jynnantonix approved these changes

2023-02-15 02:20 UTC, jynnantonix commented on sdk/vaa/payloads.go
> +	}
```suggestion
	count := copy(reason, r.Reason)
	for i := range reason[count:] {
		reason[i] = ' '
	}
```

2023-02-15 02:20 UTC, jynnantonix commented on node/cmd/guardiand/adminserver.go
> +// tokenBridgeUpgradeContract converts a nodev1.TokenBridgeRegisterChain message to its canonical VAA representation.
nit: This doc comment is out-of-date.

2023-02-15 07:58 UTC, hendrikhofstadt approved these changes

2023-02-15 13:13 UTC, bruce-riley approved these changes

2023-02-15 14:23 UTC, conorpp commented on sdk/rust/core/src/token.rs
>                          "invalid value: {v}, expected one of 1, 2"
will update in subsequent PR

2023-02-15 14:23 UTC, merged