whitepapers: Update Governor whitepaper
wormhole-foundation/wormhole pull request #2401
Opened 2023-02-17 22:20 UTC by tbjump

* expand section explaining the reasons for defense-in-depth
* add clarity around limit vs. delay
* add FAQ section

2023-02-21 13:19 UTC, bruce-riley approved these changes

2023-02-21 13:19 UTC, bruce-riley commented on whitepapers/0007_governor.md
> +* Protect against sybil attacks.
Can you expand this sentence so people don't need to google "sybil attach"?

2023-02-21 13:19 UTC, bruce-riley commented on whitepapers/0007_governor.md
> +*Configuration*: For each chain, a _single-transaction-threshold_ and a *24h-threshold* denominated in a base currency (e.g. USD) is specified [here](https://github.com/wormhole-foundation/wormhole/b
Can you explicitly state that the governor only monitors chains and tokens that are in the configuration?

2023-02-21 13:19 UTC, bruce-riley commented on whitepapers/0007_governor.md
> +    - The above answer explains that transactions can be delayed during high utilization times.  However, the maximum possible wait time is 24hrs, though most transactions have no delay.
Is it worth mentioning that the guardian operator can manually extend the 24 hour timer if they need more time to investigate?

2023-02-25 17:01 UTC, hendrikhofstadt reviewed
I'm not sure these types of FAQs live in a design doc. They are probably a better fit for documentation as they just restate the more technical explanation in layman's terms

2023-02-27 13:16 UTC, bruce-riley approved these changes

2023-03-08 16:21 UTC, evan-gray requested changes
Similar to @hendrikhofstadt 's comment, I just enabled the wiki feature, perhaps that will be a good home for a plain english description of features.

2023-08-25 16:09 UTC, tbjump commented
Addressed reviewer feedback: Removed the FAQ section

2023-09-01 18:12 UTC, bruce-riley approved these changes

2023-09-01 18:16 UTC, evan-gray approved these changes

2023-09-01 18:17 UTC, merged