Node: Circle Integration governance support
wormhole-foundation/wormhole pull request #2444
Opened 2023-02-27 17:06 UTC by bruce-riley

This PR implements the governance actions needed for Circle Integration.

Fixes https://github.com/wormhole-foundation/wormhole-circle-integration/issues/27

`$ build/bin/guardiand template circle-integration-update-wormhole-finality --finality 42
current_set_index:  3
messages:  {
  sequence:  14607295174026133158
  nonce:  3776518587
  circle_integration_update_wormhole_finality:  {
    finality:  42
  }
}`
`$ build/bin/guardiand template circle-integration-register-emitter-and-domain --foreign-emitter-chain-id 2 --foreign-emitter-address 0x75Bfa155a9D7A3714b0861c8a8aF0C4633c45b5D --circle-domain 12345
current_set_index:  3
messages:  {
  sequence:  17227086764769013959
  nonce:  3938568023
  circle_integration_register_emitter_and_domain:  {
    foreign_emitter_chain_id:  2
    foreign_emitter_address:  "00000000000000000000000075bfa155a9d7a3714b0861c8a8af0c4633c45b5d"
    circle_domain:  12345
  }
}`
`$ build/bin/guardiand template circle-integration-upgrade-contract-implementation --new-implementation-address 0x75Bfa155a9D7A3714b0861c8a8aF0C4633c45b5D
current_set_index:  3
messages:  {
  sequence:  4915487998059910641
  nonce:  1159380270
  circle_integration_upgrade_contract_implementation:  {
    new_implementation_address:  "00000000000000000000000075bfa155a9d7a3714b0861c8a8af0c4633c45b5d"
  }
}`

2023-02-28 18:28 UTC, panoel approved these changes
I looked at everything except what is in the sdk/vaa directory

2023-03-02 11:04 UTC, hendrikhofstadt requested changes
See inline comments

2023-03-03 13:43 UTC, bruce-riley commented on proto/node/v1/node.proto
> +    CircleIntegrationUpdateWormholeFinality circle_integration_update_wormhole_finality = 18;
If you're asking why I started with 18, it's because 17 is used at line 89.

2023-03-03 13:44 UTC, bruce-riley commented on sdk/vaa/payloads.go
> +	// BodyCircleIntegrationUpgradeContractImplementation is a governance message to ugrade the contract implementation for Circle Integration.
Fixed.

2023-03-03 14:37 UTC, bruce-riley commented on node/cmd/guardiand/adminserver.go
> +	v := vaa.CreateGovernanceVAA(timestamp, nonce, sequence, guardianSetIndex,
Fixed.

2023-03-03 14:37 UTC, bruce-riley commented on node/cmd/guardiand/adminserver.go
> +			ForeignEmitterChainId: vaa.ChainID(req.ForeignEmitterChainId),
Fixed.

2023-03-03 17:40 UTC, panoel approved these changes

2023-03-06 07:45 UTC, hendrikhofstadt approved these changes

2023-03-06 07:45 UTC, hendrikhofstadt commented on proto/node/v1/node.proto
> +    CircleIntegrationUpdateWormholeFinality circle_integration_update_wormhole_finality = 18;
Oh missed that!

2023-03-06 15:49 UTC, conorpp approved these changes

2023-03-06 19:23 UTC, merged