Node/Watcher/EVM: Fix TimeOfBlockByHash
wormhole-foundation/wormhole pull request #2517
Opened 2023-03-13 20:43 UTC by bruce-riley

Discovered in the geth documentation that it is possible to use `HeaderByHash()` rather than `BlockByHash()` for `TimeOfBlockByHash()` since we don't need all the details. This only requires one RPC call instead of two. Also, `HeaderByHash()` works for all the chains that currently require a special version of `TimeOfBlockByHash()` because `BlockByHash()` fails.

2023-03-13 22:05 UTC, panoel approved these changes

2023-03-14 02:06 UTC, evan-gray requested changes
If `NewConnectorWithGetTimeOfBlockOverride` is no longer used with this, can it be removed?

2023-03-14 11:11 UTC, hendrikhofstadt approved these changes
Nice simplification! LGTM + evan's comment

2023-03-14 11:52 UTC, bruce-riley commented
Deleted the obsolete file.

2023-03-14 12:40 UTC, panoel approved these changes

2023-03-14 12:43 UTC, hendrikhofstadt approved these changes

2023-03-14 12:55 UTC, evan-gray approved these changes

2023-03-14 13:21 UTC, merged