Update issue templates to use the new tasklist markdown
wormhole-foundation/wormhole pull request #2539
Opened 2023-03-20 21:03 UTC by aadam-10

closes #2538

Updates the tracking issue template to use the new tasklist markdown that synergizes better with Projects

2023-03-21 10:05 UTC, hendrikhofstadt approved these changes

2023-03-21 10:06 UTC, hendrikhofstadt requested changes
See inline comments

2023-03-21 10:06 UTC, hendrikhofstadt commented on .github/ISSUE_TEMPLATE/tracking_issue.md
>  ### Task list
Should the header be outside the code block?

2023-03-23 13:31 UTC, hendrikhofstadt approved these changes

2023-04-05 13:58 UTC, bruce-riley commented
Looks like a rebase went awry on this?

2023-04-06 13:40 UTC, aadam-10 commented
seems like, thanks for the headsup - I'll make a fresh pr bc I'm not sure how to fix it

2023-04-06 13:40 UTC, closed without merging