Enhancing the SDK repairVAA functionality for multipleChain
wormhole-foundation/wormhole pull request #2542
Opened 2023-03-22 14:25 UTC by wasif28

Enhancing the SDK repairVAA functionality for multipleChain out of the box to support all chains for MAINNET, TESTNET, DEVNET

2023-03-24 17:49 UTC, kev1n-peters commented on sdk/js/src/utils/repairVaa.ts
> +  chainId: ChainId,
I think we should add support for non-EVM chains or at least set the type here to `EVMChainId`.

2023-04-05 10:29 UTC, wasif28 commented
@kev1n-peters  have done the suggested changes kindly give it a glance

2023-04-05 14:19 UTC, evan-gray requested changes
@wasif28 can you provide some background as to why this function needs to provide support for other chains or environments? Wormhole currently uses Ethereum as it's source of truth for guardian sets, so my understanding was this function was meant to match that (as it's what the guardian uses).

Furthermore, there is only one guardian set in devnet and testnet, so what is the rationale for adding those to this function?

2023-04-16 00:03 UTC, evan-gray commented
Closing per my comment above. Feel free to open a discussion regarding your use case.

2023-04-16 00:03 UTC, closed without merging