clients/js: add unit tests on worm CLI
wormhole-foundation/wormhole pull request #2631
Opened 2023-04-13 00:21 UTC by AlberErre

Resolves #2596 

This PR adds unit tests  for `cmds` commands on worm CLI 🔒🚓 located on `client/ts/__tests__`

In order to run them, you need to navigate to `client/js` folder and run:

```
npm run test
```

Also, a `jest.config.json` file has been added to configure `jest` testing environment.

----

🚨 Note:  In order to test a command module, it needs to export all the module properties, following this [documentation](https://github.com/yargs/yargs/blob/main/docs/advanced.md#providing-a-command-module). 

There are some missing tests modules on this PR, such as `evm`, `aptos`, `generate`. These modules need refactor to be able to test them, as they don't expose all the required interfaces, in particular `exports.handler`. 

This refactor should be implemented in the future, as it's beyond the scope of this PR.

2023-04-16 21:29 UTC, AlberErre commented
@heyitaki @kcsongor @aadam-10 @evan-gray could you take a look at this? 👀 

feedback and suggestions are more than welcome! 🙏🏼 🚀

2023-05-09 22:13 UTC, AlberErre commented
Hey @aadam-10 @heyitaki @evan-gray sorry to bother again, is there any chance to review this? 🙏🏼 

it's starting to diverge a lot from `main` branch 👀 🙏🏻

2023-05-09 22:17 UTC, heyitaki commented
Hey @AlberErre, I'm hoping to merge in the #2885 stack first. There will likely be merge conflicts, but I'm happy to make those changes and push the PR through once that happens!

2023-06-08 15:51 UTC, heyitaki commented
@AlberErre can you explain why the tests for the positional arguments are useful? I'm inclined to remove them... IMO as long as the functionality isn't broken and those corresponding tests pass it should be fine for a contributor to edit arg values/positions.

2023-06-08 18:38 UTC, AlberErre commented
These commands are directly exposed to end users using worm CLI, therefore everyone relying on them will suffer breaking changes if we mess with them 👀.

It's similar to exposing a REST API. As long as new changes are extensible, we would be good to go and these tests won't break ✅. On the other hand, if the current public API is changed, these tests will break ❌, therefore notifying us that we are probably affecting end users with this change (in which case we will need to either avoid this change, or notify it on the README/CHANGELOG files). 

The point is that these commands are public, and therefore should be relatively stable. If these commands wouldn't be publicly exposed, we could indeed change them at our will, but it's not the case.

The idea is to provide a simple test suite emulating the flags and args expected on each command by end users, to figure out if we break them in future refactors 👀🏄‍♂️

2023-06-21 19:00 UTC, AlberErre commented
now we can download the HTML test report directly from Github Actions 🎉, it's stored as an artifact on the pipeline. 

Here is an example: 
https://github.com/AlberErre/wormhole/actions/runs/5337687871

2023-06-21 19:10 UTC, AlberErre commented
@aadam-10 @heyitaki @a5-pickle 

Just merged `main` to sync ✅, ready to review 👍🏻

2023-06-28 15:16 UTC, evan-gray requested changes
This is a lot of code which doesn't seem meaningfully more significant than this docs generation check that was added. Is this PR / design worth the maintenance overhead? https://github.com/wormhole-foundation/wormhole/blob/main/.github/workflows/build.yml#L256C11-L256C11

Tests that check the functionality could be good, but simple naming checking may be covered by the above.

2023-06-29 10:49 UTC, AlberErre commented
Hey @evan-gray @aadam-10 just checked this new `make docs` command and looks good to auto-generate documentation for README files.

That said, I wouldn't use it for testing as they don't check the real implementation output ❌. 

👀 Rather, this is testing the output generated by `clients/js/src/doc.ts`, which is an abstraction layer we're implementing on top of `worm CLI` that could contain bugs or provide false positives.

🚨 Actually, this is what is happening right now on the `main` branch. As the README file is showing commands that doesn't exist such as `worm verify-vaa init-token-bridge` (https://github.com/wormhole-foundation/wormhole/blob/main/clients/js/README.md?plain=1#L941), among others.

I know these CLI tests could look like adding some unnecessary overhead, but they are more robust and secure ✅, as we're using the final executable (the same as end-users are using) to verify the implementation is working as expected (without any intermediate layer that could contain bugs).

2023-07-04 23:38 UTC, AlberErre commented
@evan-gray just updated & deleted some tests as you suggested 👀

Also, I've added a more generic approach (and easy to maintain) to test command names with args. Now, we relay on README documentation generated by `clients/js/src/doc.ts` to tests these commands 🎉.

This way we still are comparing against the real implementation output ✅, but using README auto-generated docs to compare with. This ensures that documentation generation logic & worm CLI are in sync and produce the same output.

Some refactor has been needed to obtain a single source of commands to derive everything from. As a result, we now have a single source of truth in `src/cmds/index.ts`, regarding commands to be expected on both CLI usage & documentation.

This way, @kcsongor we don't need to maintain several arrays with the latest commands (e.g.  as commented here -> https://github.com/wormhole-foundation/wormhole/pull/3153#issuecomment-1613551798 for `doc.ts`), as now they're all defined on `src/cmds/index.ts`. 

Let me know what you think 👀, these tests are now far way easy to maintain, as well as still robust and secure ✅

2023-07-06 15:08 UTC, AlberErre commented
@aadam-10 @heyitaki @a5-pickle @evan-gray @kcsongor

Just merged main to sync again ✅ , ready to review 🎉

2023-07-13 18:19 UTC, heyitaki requested changes

2023-07-13 18:19 UTC, heyitaki commented on clients/js/src/main.ts
> +  .command(CLI_COMMAND_MODULES as YargsCommandModule[])
Why were you able to type `CLI_COMMAND_MODULES` directly as `YargsCommandModule[]` here, as opposed to using an intermediate `unknown` here? https://github.com/wormhole-foundation/wormhole/pull/2631/files#diff-e464885dd3e2f3456057320cb9e66fe189333a5eef5c2786cb027450ec52b445R11

2023-07-13 18:22 UTC, heyitaki commented on clients/js/src/main.ts
> +  .command(CLI_COMMAND_MODULES as YargsCommandModule[])
I see this was answered, so marking as resolved. https://github.com/wormhole-foundation/wormhole/pull/3182/files#r1258347392

2023-07-13 19:49 UTC, AlberErre commented on clients/js/__tests__/utils/getters.ts
> +  return ["mainnet", "testnet", "devnet"] as WormholeSDKNetwork[];
You're 100% right ✅, just changed it to a const list

2023-07-13 19:49 UTC, AlberErre commented on clients/js/__tests__/utils/getters.ts
> +export type WormholeSDKNetwork = "mainnet" | "testnet" | "devnet";
This was initially to type `getNetworks` method, just deleted this type as well ✅

2023-07-13 20:02 UTC, AlberErre commented on clients/js/package.json
> +    "jest-html-reporters": "^3.1.4",
This is useful while tests are failing in the pipeline 🚨

By using this HTML report we can see which tests are failing (and why) more easily 🏄‍♂️. The current alternative is scrolling through CLI (Jest) error output, which is harder to read and reason about.

Regarding slimming our dependency list, this package is included in `devDependencies` 👀 . Therefore this dependency won't be included in the Worm CLI `main.js` executable output, and won't increase bundle size.

This dependency would only live during the lifespan of the Github Action, similar to what `Jest` dependency does.

2023-07-13 20:09 UTC, AlberErre commented on clients/js/__tests__/recover.test.ts
> +    const expectedAddress = "0x6FbEBc898F403E4773E95feB15E80C9A99c8348d";
Yes exactly, I launched this command manually with the mocked `digest` and `signature` values, and received this `expectedAddress` value in return.

I assumed the current implementation was correct, and therefore we can leverage on this result as a test case 👀

2023-07-15 00:05 UTC, heyitaki commented on clients/js/package.json
> +    "jest-html-reporters": "^3.1.4",
Hmm CLI output is usually enough for me, but can't hurt I guess 🤷

2023-07-15 00:06 UTC, heyitaki approved these changes

2023-07-23 11:11 UTC, AlberErre commented
An extension of this PR (covering `worm submit` command) has been created here: https://github.com/wormhole-foundation/wormhole/pull/3229

2023-07-23 13:19 UTC, AlberErre commented on clients/js/package.json
> +    "jest-html-reporters": "^3.1.4",
@heyitaki just removed the HTML report generation on the next PR 👍 https://github.com/wormhole-foundation/wormhole/pull/3229

2024-03-14 13:16 UTC, evan-gray commented
Closing this as some of these tests do not appear to be sufficiently meaningful or are already covered by other tests of the CLI. For example, the README.md is more efficiently covered by [the check](https://github.com/wormhole-foundation/wormhole/blob/main/.github/workflows/build.yml#L256) added in #3058

2024-03-14 13:16 UTC, closed without merging