gRelayer: Uses calls upper bounded on return data length for deliveries.
wormhole-foundation/wormhole pull request #2934
Opened 2023-05-15 23:02 UTC by scnale

This prevents excessive gas usage from contracts that return big and complex errors or even maliciously crafted revert buffers.

WIP: missing tests for these big revert buffers.

2023-05-24 20:51 UTC, nonergodic requested changes

2023-05-24 20:51 UTC, nonergodic commented on ethereum/contracts/relayer/coreRelayer/CoreRelayerDelivery.sol
> +
`postGas` should be determined here rather than further down

2023-05-24 20:51 UTC, nonergodic commented on ethereum/contracts/relayer/coreRelayer/CoreRelayerDelivery.sol
> +    (bool success, bytes memory returnedData) = returnLengthBoundedCall(
`preGas` should be determined here

2023-05-24 20:51 UTC, nonergodic commented on ethereum/contracts/relayer/coreRelayer/CoreRelayerDelivery.sol
> +        vaaInfo.deliveryVaaHash,
:heart:

2023-05-24 20:51 UTC, nonergodic commented on ethereum/contracts/relayer/coreRelayer/Utils.sol
> +    mstore(freeMemoryPtr, newFreeMemoryPtr)
love the doc and the efficiency (compared to the lazy implementation of using `new bytes(lengthBound)` before and a `.slice(actualLength)` after)

2023-05-24 21:30 UTC, scnale commented on ethereum/contracts/relayer/coreRelayer/Utils.sol
> +uint256 constant returnLengthBound = 132;
Yeah, it makes sense. The code generated will probably differ but I don't think it makes any sense to hardcode it in `Utils.sol`. I even had to include a test to ensure consistency in the constant value :pensive:

2023-05-30 17:41 UTC, nonergodic approved these changes

2023-05-30 18:45 UTC, merged