node/watchers: Log each watcher's config on startup
wormhole-foundation/wormhole pull request #3076
Opened 2023-06-12 16:59 UTC by tbjump

This PR is part of the testing strategy for https://github.com/wormhole-foundation/wormhole/pull/3024

2023-06-12 16:59 UTC, tbjump commented
Current dependencies on/for this PR:
* main
  * **PR #3076** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3076" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3076?utm_source=stack-comment).

2023-06-12 18:52 UTC, bruce-riley requested changes
Sorry, I just deleted the wormchain watcher, so I think you are going to have to deal with a merge conflict.

2023-06-13 16:41 UTC, tbjump commented
addressed merge conflicts

2023-06-13 17:37 UTC, evan-gray approved these changes

2023-06-13 17:37 UTC, SEJeff approved these changes

2023-06-13 17:38 UTC, merged