sdk: WormholeRelayer mainnet addresses
wormhole-foundation/wormhole pull request #3108
Opened 2023-06-20 21:28 UTC by JoeHowarth

Adds WormholeRelayer mainnet addresses - which are all the same 🎉

2023-06-20 22:29 UTC, derpy-duck requested changes

2023-06-20 22:29 UTC, derpy-duck commented on sdk/js/src/relayer/consts.ts
> +  ethereum: {
Also this is the delivery provider address, not the wormhole relayer address

2023-06-21 14:45 UTC, JoeHowarth commented on sdk/js/src/relayer/consts.ts
> +  ethereum: {
https://github.com/wormhole-foundation/wormhole/commit/a7120bbfbdb8deb6e6ba374e452f8faa9d281b3e#diff-4902563da8bf920854962c86bf209642fbd053137b6270307b2221a24cf46596

basing off this ^

And good catch on the deliveryProvider! Fixed

2023-06-21 19:26 UTC, derpy-duck commented on sdk/js/src/relayer/consts.ts
> +  },
Missing Arbitrum and Optimism

2023-06-21 19:40 UTC, derpy-duck submitted a review, later dismissed

2023-06-21 20:05 UTC, kev1n-peters submitted a review, later dismissed

2023-06-22 19:47 UTC, derpy-duck approved these changes

2023-06-22 20:12 UTC, kev1n-peters approved these changes

2023-06-22 20:13 UTC, merged