Support Celo native's credit and debit gas fee functions
wormhole-foundation/wormhole pull request #3162
Opened 2023-07-03 21:28 UTC by martinvol

2023-07-05 19:04 UTC, evan-gray commented on ethereum/contracts/bridge/token/TokenImplementation.sol
> +    modifier onlyCeloChains() {
Perhaps we should use the Wormhole chain id here.

2023-07-05 19:11 UTC, evan-gray commented on ethereum/contracts/bridge/token/TokenImplementation.sol
> +    modifier onlyCeloChains() {
Or maybe not because this is in the token 🤔

2023-07-19 15:25 UTC, gator-boi requested changes
A few of us have discussed how to include this change in the existing `TokenImplementation` contract. 

How do you feel about creating a second `TokenImplementation` contract with the Celo-specific functionality that inherits from the existing contract? This way the Celo-specific code is not deployed to other blockchains when the `TokenImplementation` contract is upgraded.

2023-07-19 15:33 UTC, martinvol commented
Yeah, makes sense.

My original intention with this PR was to pull it in front of your team so you could suggest me the better course of action.

Even if this code gets deployed only on Celo, I'd still include the checks to make sure the chain is actually Celo compatible.

2024-04-26 14:37 UTC, SEJeff commented
@martinvol do you still want to work on this?

2025-05-23 15:48 UTC, djb15 commented
Closing as part of cleanup. The branch can be retrieved [here](https://github.com/wormhole-foundation/wormhole-branch-clone) and the PR reopened from a fork if required.

2025-05-23 15:48 UTC, closed without merging