allow custom block range
wormhole-foundation/wormhole pull request #3188
Opened 2023-07-12 14:20 UTC by derpy-duck

2023-07-12 14:24 UTC, kev1n-peters approved these changes

2023-07-12 15:14 UTC, kev1n-peters approved these changes

2023-07-12 15:29 UTC, kcsongor requested changes
overall makes sense, it would make sense to suggest the flag in the error string when the delivery is not found

2023-07-12 15:29 UTC, kcsongor commented on clients/js/src/cmds/status.ts
> +    .positional("blockStart", {
for arg names we use `block-start` format elsewhere

2023-07-12 15:29 UTC, kcsongor commented on clients/js/src/cmds/status.ts
> +    .positional("blockEnd", {
same as above

2023-07-12 22:34 UTC, kcsongor approved these changes

2023-07-13 02:58 UTC, kev1n-peters approved these changes

2023-07-13 14:09 UTC, merged