Node: Reduce auto reobservation requests
wormhole-foundation/wormhole pull request #3203
Opened 2023-07-13 16:21 UTC by bruce-riley

2023-07-13 16:40 UTC, panoel submitted a review, later dismissed

2023-07-13 18:17 UTC, tbjump approved these changes
Here is a PR that rebases this change on the test improvements: https://github.com/wormhole-foundation/wormhole/pull/3205 
The unit tests there are passing and the code coverage is good, so I'm fine with merging this in to main.

2023-07-13 18:20 UTC, tbjump commented
Current dependencies on/for this PR:
* main
  * **PR #3203** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3203" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #3207** <a href="https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3207" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/wormhole-foundation/wormhole/3203?utm_source=stack-comment).

2023-07-13 18:23 UTC, panoel approved these changes

2023-07-13 18:24 UTC, evan-gray requested changes

2023-07-13 18:24 UTC, evan-gray commented on node/pkg/processor/cleanup.go
> +		p.logger.Debug("VAA already in DB but hash is different", zap.String("old_hash", oldHash), zap.String("new_hash", hash))
is this missing a `return false, nil`

2023-07-13 18:36 UTC, tbjump approved these changes

2023-07-13 18:44 UTC, bruce-riley commented on node/pkg/processor/cleanup.go
> +		p.logger.Debug("VAA already in DB but hash is different", zap.String("old_hash", oldHash), zap.String("new_hash", hash))
Apparently @tbjump fixed this.

2023-07-13 19:56 UTC, panoel approved these changes

2023-07-14 13:33 UTC, evan-gray approved these changes

2023-07-14 13:34 UTC, merged