Node/Gov: Update floor prices
wormhole-foundation/wormhole pull request #3255
Opened 2023-08-02 19:37 UTC by bruce-riley

This PR updates to governor floor prices. Note that a few symbols were added / removed from the manual token list because the were removed / added from the TVL  list.

I verified that the CoinGecko query still works.

2023-08-02 20:03 UTC, tbjump requested changes
It would be nice if there was some way to specify a list of important tokens (e.g. all native tokens, all stablecoins) that should be included no matter what the TVL list produces. 
Bonus if there could be a hardcoded floor price and a test that enforces that the new generated floor price is greater or equal to the hardcoded floor price. 
That would provide overall more assurance that the generation of generated_mainnet_tokens.go is correct. 

If you don't want to solve it in this PR, I'd also be fine with having that as a ticket to follow-up on.

2023-08-02 20:09 UTC, evan-gray approved these changes
looks like the appropriate generated output to me

2023-08-02 20:28 UTC, panoel approved these changes

2023-08-03 13:21 UTC, tbjump approved these changes

2023-08-03 14:07 UTC, merged