Setparams gov vaa
wormhole-foundation/wormhole pull request #3285
Opened 2023-08-12 23:01 UTC by nik-suri

2023-08-13 03:27 UTC, evan-gray requested changes
I feel this could be made more generic, like `InPlaceUpgrade` or something with a payload  so if we ever have to do something like this again we don't need to make all these code changes all over again but just update a case statement where like `1` is `SetTokenFactoryPfmDefaultParams` but, you know, `2` could do the next thing we need to do in the future

2023-08-14 14:55 UTC, bruce-riley submitted a review, later dismissed

2023-08-14 15:24 UTC, bruce-riley approved these changes

2023-08-14 15:52 UTC, misko9 commented on wormchain/proto/wormhole/tx.proto
> +  MsgSetTokenFactoryPfmDefaultParams set_tokenfactory_pfm_default_params = 2;
Can `MsgSetTokenFactoryPfmDefaultParams set_tokenfactory_pfm_default_params = 2` be remove and replaced with `bytes vaa = 2`? Then, msgServer InPlaceUpgrade parses and verifies VAA, and performs the appropriate execution based on the Action?

2023-08-14 18:10 UTC, evan-gray requested changes
okay, I realized we have an opportunity to save some lines of code here. can we make just one handler for `execute_gateway_governance_vaa` that will perform the verification and switch on `action`? 🙏 this could include handling the one from @misko9 's PR that was just merged, since it hasn't been released yet

2023-08-14 22:02 UTC, evan-gray submitted a review, later dismissed

2023-08-14 22:25 UTC, misko9 reviewed
This should be 0

2023-08-14 22:27 UTC, misko9 commented on wormchain/x/wormhole/client/cli/tx_execute_gateway_governance_vaa.go
>  			vaaBz, err := hex.DecodeString(args[1])
args[1] should be args[0]

2023-08-14 22:35 UTC, nik-suri commented on node/cmd/guardiand/admintemplate.go
> +	// GatewaySetTokenfactoryPfmDefaultParamsCmd doesn't have any flags
Updated naming of the governance messages to be consistent.

2023-08-14 23:08 UTC, bruce-riley approved these changes

2023-08-15 00:37 UTC, evan-gray approved these changes

2023-08-15 00:37 UTC, merged