CCQ/Node/EVM: Refactor
wormhole-foundation/wormhole pull request #3542
Opened 2023-11-16 20:23 UTC by bruce-riley

This code reduces the amount of code that is duplicated between the `eth_call`, `eth_call_by_timestamp` and `eth_call_with_finality`.

2023-11-20 22:41 UTC, panoel commented on node/pkg/watchers/evm/ccq.go
>  		w.ccqLogger.Error("invalid block id hints in eth_call_by_timestamp query request, if one is unset they both must be unset",
Can you say something like, "both should be either set or unset"?

2023-11-20 22:44 UTC, panoel commented on node/pkg/watchers/evm/ccq.go
>  		blockNum, nextBlockNum, found := w.ccqTimestampCache.LookUp(req.TargetTimestamp / 1000000)
Isn't milliseconds to seconds => divide by 1000?

2023-11-20 22:59 UTC, panoel commented on node/pkg/watchers/evm/ccq.go
> +				err = fmt.Errorf("call %d failed: %w", idx, evmCD.callErr)
When you format these err's in this function, will only the last error be returned?

2023-11-20 22:59 UTC, panoel approved these changes

2023-11-27 19:12 UTC, evan-gray requested changes

2023-11-27 19:12 UTC, evan-gray commented on node/pkg/watchers/evm/ccq.go
> +// ccqBuildBatchFromCallData builds two slices. The first is the batch submitted to the RPC call. It contains one entry for each query plus one to query the block.
feel like I'm missing something - this function name is different but the calls remain to `ccqBuildBatchFromCallData`

2023-11-27 19:12 UTC, evan-gray commented on node/pkg/watchers/evm/ccq.go
> +	evmCallData := EvmCallData{}
should this have changed from an array?

2023-11-27 19:12 UTC, evan-gray commented on node/pkg/watchers/evm/ccq.go
>  	batch := []rpc.BatchElem{}
there are two of these method names now - one on the watcher and one not. was the name change an accident?

2023-11-27 19:24 UTC, evan-gray submitted a review, later dismissed

2023-11-28 01:24 UTC, panoel approved these changes

2023-11-28 14:26 UTC, evan-gray approved these changes

2023-11-28 14:26 UTC, evan-gray commented on node/pkg/watchers/evm/ccq.go
> +		w.ccqLogger.Debug("published query response error to handler")
this isn't just for errors anymore.

2023-11-28 14:26 UTC, evan-gray commented on node/pkg/watchers/evm/ccq.go
> +		w.ccqLogger.Error("failed to published query response error to handler")
same here

2023-11-28 14:51 UTC, merged