sdk/js: handling valid exceptions
wormhole-foundation/wormhole pull request #3590
Opened 2023-12-09 08:08 UTC by Abhishekkochar

fix: #3190

2023-12-09 08:37 UTC, Abhishekkochar commented
@kcsongor, Please have a look.

2023-12-12 22:04 UTC, kcsongor commented on sdk/js/src/token_bridge/__tests__/algorand-integration.ts
> +            success = true;
shouldn't this be the other way around?

2023-12-12 22:04 UTC, kcsongor commented on sdk/js/src/token_bridge/__tests__/algorand-integration.ts
> +            success = true;
this one too

2023-12-12 22:05 UTC, kcsongor commented on sdk/js/src/token_bridge/__tests__/aptos-integration.ts
> +      if(e instanceof Error && e.message.includes("wrapped asset already exists")){
does the error message actually contain this?

2023-12-12 22:06 UTC, kcsongor requested changes
Did you run these tests locally?

2023-12-19 11:54 UTC, Abhishekkochar commented on sdk/js/src/token_bridge/__tests__/algorand-integration.ts
> +            success = true;
Oh yes. Fixed. Will push soon.

2023-12-19 11:56 UTC, Abhishekkochar commented
@kcsongor, Can you please confirm if this is correct [algogrand/package](https://github.com/wormhole-foundation/wormhole/blob/main/algorand/package.json#L14)?
There is no test.ts file in test dir.

2023-12-19 12:05 UTC, Abhishekkochar commented
> Did you run these tests locally?

I have tried to run them. There is an error when running alogrand tests?

2024-03-14 21:28 UTC, evan-gray commented
This error case is only hit when the tests are run a second time on an existing tilt instance. This never happens in CI and is only a hinderance to a developer trying to run the tests without cycling the corresponding chains. Given that the subsequent test cannot pass if the token was not properly attested, the existing code is adequate for CI. So, for the benefit of devs in this repo, it seems a more prudent thing would be to skip the test step altogether if the token was already attested.

2024-03-14 21:28 UTC, closed without merging