Eth: Upgrade scripts
wormhole-foundation/wormhole pull request #3921
Opened 2024-05-01 17:46 UTC by bruce-riley

2024-05-01 17:55 UTC, evan-gray requested changes

2024-05-01 17:55 UTC, evan-gray commented on ethereum/env/.env.avalanche.testnet
Everything in this file indicates it is for BNB Smart Chain Testnet https://chainlist.org/chain/97

2024-05-01 19:15 UTC, bruce-riley commented on ethereum/env/.env.avalanche.testnet
Oops! Fixed it.

2024-05-01 19:29 UTC, evan-gray approved these changes

2024-05-02 14:40 UTC, kcsongor approved these changes

2024-05-02 14:49 UTC, merged