Replace Terra2 RPCs with new endpoint
wormhole-foundation/wormhole pull request #3937
Opened 2024-05-09 12:02 UTC by terencelimzhengwei

https://phoenix-lcd.terra.dev is being deprecated. The new LCD for Terra2 is https://lcd-terra.tfl.foundation

2024-05-09 12:20 UTC, bruce-riley approved these changes

2024-05-09 12:32 UTC, evan-gray requested changes
If it is the case this will be deprecated (I could not immediately find supporting documentation). I would sooner recommend switching to `https://terra-lcd.publicnode.com/`

2024-05-09 13:26 UTC, terencelimzhengwei commented
@evan-gray - i'm from Terraform Labs. We have not put out comms regarding this yet, but we have swapped out the phoenix LCD endpoint to the lcd-terra endpoint in all our repos. An example here (https://github.com/terra-money/station-assets/blob/main/chains/mainnet/terra.js). 

Swapping to publicnode.com works as well if that is what the wormhole team prefers. But just wanted to notify that we've updated the URL of our public infra. Comms and docs will be updated over the next few days.

2024-06-03 18:27 UTC, evan-gray commented
As far as I can tell, [the docs](https://docs.terra.money/develop/endpoints/) have not been updated. Closing for the time being.

2024-06-03 18:27 UTC, closed without merging