change ioutil to io and os
wormhole-foundation/wormhole pull request #3970
Opened 2024-06-06 15:11 UTC by charltonliv

According to https://pkg.go.dev/io/ioutil.
> Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code. See the specific function documentation for details.

This PR changes those deprecated packages to the new one.

2024-06-07 17:13 UTC, evan-gray requested changes

2024-06-08 00:38 UTC, charltonliv commented on wormchain/x/wormhole/client/cli/genesis.go
> +	bz, err := io.ReadFile(filePath)
Whoops, it should be `os.ReadFile`, I've pushed https://github.com/wormhole-foundation/wormhole/pull/3970/commits/8c7b0f805766c4d3f1f4b73a2cfbcb048053dda4 that will solve this.

2024-07-24 12:45 UTC, evan-gray approved these changes

2024-07-30 17:23 UTC, nik-suri approved these changes

2024-07-30 17:24 UTC, merged

2024-07-31 02:10 UTC, charltonliv commented
🥳