Update wormchain CODEOWNERS
wormhole-foundation/wormhole pull request #4094
Opened 2024-08-22 20:34 UTC by nik-suri

Add @johnsaigle @mdulin2 @jtieri as codeowners for wormchain

2024-08-23 05:57 UTC, evan-gray requested changes
According to the checker, this codeowners file has an error.

2024-08-23 14:40 UTC, jtieri commented
> According to the checker, this codeowners file has an error.

this is probably a permissions issue, i believe codeowners must also have write access in a repo

2024-08-24 00:01 UTC, evan-gray approved these changes

2024-08-28 13:32 UTC, johnsaigle approved these changes

2024-08-28 15:57 UTC, merged