wormchain: add slashing params vaa
wormhole-foundation/wormhole pull request #4194
Opened 2024-12-16 18:51 UTC by joelsmith-2019

This PR adds a new Wormhole core governance action payload to Wormchain, allowing guardians to update the slashing parameters. I'm unsure where I should include documentation for how the payload is structured. If theres a specific README, please let me know and I'll add some documentation on it.

```
// Signed Blocks Window (big-endian uint64)
SignedBlocksWindow uint64

// Min Signed Per Window (big-endian uint64)
MinSignedPerWindow uint64

// Downtime Jail Duration (big-endian uint64)
DowntimeJailDuration uint64

// Slash Fraction DoubleSign (big-endian uint64)
SlashFractionDoubleSign uint64

// Slash Fraction Downtime (big-endian uint64)
SlashFractionDowntime uint64
```

Ref to Cosmos SDK Slashing Params: [Params](https://github.com/cosmos/cosmos-sdk/blob/release/v0.45.x/x/slashing/types/params.go)

2024-12-18 14:23 UTC, bruce-riley submitted a review, later dismissed
I only reviewed the sdk stuff.

2025-01-10 19:04 UTC, johnsaigle approved these changes

2025-01-13 19:14 UTC, joelsmith-2019 commented
@bruce-riley would you be able to re-review this after the few minor changes I added last week?

2025-01-14 00:07 UTC, bruce-riley approved these changes
I only reviewed the `sdk/vaa` changes. I am not an owner of anything else.

2025-01-15 17:49 UTC, kakucodes requested changes
couple small nits here- nothing big.

2025-01-15 17:49 UTC, kakucodes commented on wormchain/x/wormhole/client/cli/genesis.go
> +			chain := 3104
can we reference wormchain by name instead of by number here so that things are a bit more readable?

2025-01-15 17:49 UTC, kakucodes commented on wormchain/x/wormhole/keeper/msg_server_execute_governance_vaa_test.go
> +	_ = privateKeys
can this be safely removed.

2025-01-15 17:55 UTC, kakucodes approved these changes
Reviewed the code and left a couple small nits but overall everything lgtm!

2025-01-15 20:41 UTC, johnsaigle approved these changes

2025-01-27 21:45 UTC, kakucodes approved these changes

2025-01-30 13:53 UTC, bruce-riley approved these changes
Again, I only reviewed the sdk stuff.

2025-02-05 14:14 UTC, evan-gray requested changes
It looks like this governance uses the wrong module! Please confirm.

2025-02-11 14:55 UTC, johnsaigle approved these changes

2025-02-11 15:00 UTC, merged